### ISSUE TITLE
Error reading undo-tree history

### ISSUE THREAD

**Issue by hongyi-zhao** [tarsiiformes/undo-tree#3]
On Ubuntu 22.10, I'm using the latest `undo-tree` with the following configuration:

```emacs
;;https://github.com/raxod502/straight.el/issues/850#issuecomment-926557248
;;https://github.com/daviwil/emacs-from-scratch/wiki/LSP-Python-(pyright)-config-in-emacs-from-scratch#undo-tree
(use-package undo-tree
  :straight (:host github :repo "tarsiiformes/undo-tree")
  :diminish undo-tree-mode
  :config
  (global-undo-tree-mode)
  )
```

However, the following error message is often triggered:

`Error reading undo-tree history from "/home/werner/.emacs.d/var/undo-tree-hist/.!home!werner!.emacs.d!init.el.~undo-tree~"`

Any tips on how to solve this problem?

Regards,
Zhao

**Comment by tarsius** [comment]
The reasons I maintain my own version are that the upstream and gnu elpa versions diverged in the past (not so badly now though), upstream does not respond to requests, and there are many compile warnings (and in the past more serious issues I believe).

I recently rebased myu version on top of elpa and currently my commits only have to cover warnings. Maybe something went wrong in the process, so the first thing you should do is to revert to the elpa version and try with that. If you can reproduce with the elpa version, then open an issue in debbugs.

**Comment by 8dcc** [comment]
The same thing happened to me.

When opening a file:

```
Error reading undo-tree history from "/home/username/.emacs.d/undo/.!home!username!src!main.c.~undo-tree~"
```

When using `M-x undo-tree-load-history`:

```
user-error: Error reading undo-tree history from "/home/username/.emacs.d/undo/.!home!username!src!main.c.~undo-tree~"
```

My undo-tree config:

```emacs-lisp
(use-package undo-tree
  :diminish
  :config
  (setq undo-tree-visualizer-timestamps t)
  (add-to-list 'undo-tree-history-directory-alist
               `("." . ,(concat user-emacs-directory "undo")))
  (global-undo-tree-mode))
```
